### ISSUE TITLE
客户端文件已经识别了，但是还是不能运行

### ISSUE THREAD

**Issue by sd462355991** [kuoruan/luci-app-frpc#11]
[- 1. 客户端文件已经识别了，但是还是不能运行！！！

是不是服务端也要填？但填了也不能运行！！
](url)http://m.qpic.cn/psc?/V11nzVvG04S3c9/jct2zvxi*sJqpxBnA.Xyw3bbfQ3uP3kVUjXQ94INGAtpKJsbBMLAw8OFRTrWa1o4XPWQzQz9oomANbw95TXjK23cjsB3LwWAAPBG2N*bYCs!/b&bo=SgI9AgAAAAADF0U!&rf=viewer_4
(url)http://m.qpic.cn/psc?/V11nzVvG04S3c9/DkqUZ9iBKRJfSLPQfqcDxy3NgG6x72D6GGF6hxmCjEqbLrmmgSs4*k3esTiZU*K7H9AHb3H9RrSnmDLJ7HDNug!!/b&bo=AwIOAQAAAAADByw!&rf=viewer_4

**Comment by sd462355991** [comment]
小白一个，不知道怎么传截图，麻烦大神

**Comment by kuoruan** [comment]
配置好服务端，然后在下面选择对应的服务端

**Comment by sd462355991** [comment]
还是不行

**Comment by sd462355991** [comment]
我用frpc不是用你的
是用这个https://github.com/fatedier/frp/releases  下载的这个frp_0.30.0_linux_arm.tar.gz
然后显示找到版本：0.30.0
但是用你的https://github.com/kuoruan/openwrt-frp/releases  下载的frpc_0.30.0-1_arm_cortex-a7_neon-vfpv4.ipk
然后显示不了版本，路径也设置了，怎么弄都是找不到文件！！！
凌乱中。。。

**Comment by kuoruan** [comment]
在命令行里边执行一下 文件，看看能不能正常运行

**Comment by sd462355991** [comment]
用frpc.ini 可以运行的
cd /usr/bin
./frpc -c ./frpc.ini
没问题

**Comment by sd462355991** [comment]
开了日志显示
2020/05/07 13:20:02 [I] [service.go:249] [937d1c53f4237058] login to server success, get run id [937d1c53f4237058], server udp port [0]
2020/05/07 13:20:02 [W] [service.go:128] run admin server error: listen tcp 49.235.***.161:9999（服务器ip我打码了）: bind: cannot assign requested address
2020/05/07 13:20:02 [I] [service.go:130] admin server listen on 49.235.***.161:9999（服务器ip我打码了）
