### ISSUE TITLE
设置界面缺少远程端口，请问是哪里操作不当

### ISSUE THREAD

**Issue by jliveusa** [kuoruan/luci-app-frpc#22]
![image](https://user-images.githubusercontent.com/42428798/121643480-72999280-cac4-11eb-944e-73e242ce1a7b.png)
![image](https://user-images.githubusercontent.com/42428798/121643521-7c22fa80-cac4-11eb-8b17-1b10e006d01b.png)

**Comment by jliveusa** [comment]
已解决

**Comment by 662** [comment]
@jliveusa 怎么解决的
