### ISSUE TITLE
Frpc 无法启动

### ISSUE THREAD

**Issue by Ninzero** [kuoruan/luci-app-frpc#24]
已安装 0.37.1 版本的 openwrt-frpc 能检测到 `/usr/bin/frpc` 的版本,  但是点击 保存&应用 后无法启用, 个人怀疑是缺少 frpc.ini 配置文件所致, 想了解一下这个 frpc.ini 是存放在什么地方?

**Comment by Ninzero** [comment]
一直显示 服务未运行

**Comment by hayd1n** [comment]
也是一直显示服务未运行，求问怎么解决的？

**Comment by 10555gff** [comment]
我的也是，不知什么原因
