### ISSUE TITLE
作者您好，可以麻烦制作一个frps的luci吗

### ISSUE THREAD

**Issue by jsnjycwyz** [kuoruan/luci-app-frpc#4]
不太会改这个的源码，或者指点下如何修改，吧里面的frpc全换成frps可以吗😂

**Comment by kuoruan** [comment]
不准备做 frps，也没有必要，在路由器上起服务端的需求太少了，需要安装的话直接用命令启动 frps 就行了

**Comment by jsnjycwyz** [comment]
哦哦，好的，谢谢

**Comment by nnssz** [comment]
> 不太会改这个的源码，或者指点下如何修改，吧里面的frpc全换成frps可以吗😂

lean（coolsnowwolf）的源码里应该有 frps的luci。
